# Generated by Django 3.2 on 2021-05-02 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='accounts', serialize=False, to='challenge.user')),
                ('first_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('address1', models.CharField(max_length=64, null=True)),
                ('address2', models.CharField(max_length=64, null=True)),
                ('city', models.CharField(max_length=32, null=True)),
                ('province', models.CharField(max_length=32, null=True)),
                ('postal_code', models.CharField(max_length=16, null=True)),
                ('member_since', models.DateField(auto_now_add=True)),
                ('cash', models.DecimalField(decimal_places=2, default=250000, max_digits=10)),
            ],
        ),
    ]
