# Generated by Django 3.2 on 2021-05-27 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_tsxstock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
