# Generated by Django 3.2 on 2021-05-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_watchlist_watchlistitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holding',
            options={'ordering': ['stock_symbol']},
        ),
    ]
