# Generated by Django 3.2 on 2021-05-27 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_alter_holding_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlistitem',
            options={'ordering': ['symbol']},
        ),
    ]
