# Generated by Django 3.2 on 2021-07-02 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_alter_watchlistitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-txn_date', 'stock_symbol']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stock_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.tsxstock'),
        ),
    ]
