# Generated by Django 3.2 on 2021-07-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0013_alter_holding_stock_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
