# Generated by Django 3.2 on 2021-07-14 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0019_auto_20210714_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holding',
            options={'ordering': ['symbol']},
        ),
        migrations.RenameField(
            model_name='holding',
            old_name='stock_symbol',
            new_name='symbol',
        ),
    ]
