# Generated by Django 3.2 on 2021-07-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0020_auto_20210714_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='company_name',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Enter quantity in multiples of <b>10</b>'),
        ),
    ]
