# Generated by Django 3.2 on 2021-08-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0021_auto_20210725_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txn_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
